### PR TITLE
Fix transpose in quantizer

### PR DESCRIPTION
**Pull request by qiemem**

### CODE REVIEW

**Comment by qiemem** [comment]
Updated to a couple other fixes for corner cases, discussed in discord, plus a stability improvement. Let me know if you'd prefer the changes in separate PRs or anything.

**Review by Spyes — COMMENTED** [review]
@qiemem would you mind copy-pasting the explanation here / linking to the discussion? Thanks!

**Comment by qiemem** [comment]
Oh yes, good call. Discussion is [here](https://discord.com/channels/1054485903546003601/1054636630910173224/1055249517601112084).

Summary of how hysteresis works in the quantizer and what the stability change does:

The boundaries will be at a distance from the quantized pitch as a ratio of the distance to next lowest/highest quantized pitch. The ratio is determined by this line (and the similar line a couple down from it): https://github.com/qiemem/O_C-HemisphereSuite/blob/trig-and-tides/software/o_c_REV/braids_quantizer.cpp#L94

So, by default, the boundary will be 9/16ths of the way to the next lowest/highest number. Semitones are 128 apart. So if you're at 0 and the next highest is 128, the upper boundary will be at 9 * 128 / 16 = 72.  If you're at 128, the lower boundary will be at 7 * 128 / 16 = 56. Distance between the boundaries (which is what should be bigger than noise range to avoid instability) is then 72 - 56 = 16 for semitones. I noticed that noise on reading CV values will often be in the 20s, which is why 16 will exhibit occasional instability, so I changed the values from 9,7 to 10,6, which gives 32 for semitones instead.

Summary of bugs fixed:

- The `requantize_` flag was never reset, so if something force requantization it would *always* requantize. However, only the scale editor forces requantization so this would almost certainly not come up in practice (I found it because it affected an applet I've been working on in my personal fork). BTW, this bug is also present in original Hemisphere.
-  The + in this line and the similar line below it should be - since they're distance calculations: https://github.com/benirose/O_C-BenisphereSuite/pull/51/files#diff-d12f88b455bb5b6fb8da663af94b8e1843e7d54506161ce2eb7a975ecacebb87L80 🤦 . However, this only matters if the root is missing from the scale, since a 0 at index 0 makes the sign there not matter. And same thing in two lines below this, but it again only matters when the root is missing from the scale because the condition will always be false when the root is present with either + or -. So again, very unlikely anyone would run into this, but better to be correct.

**Comment by benirose** [comment]
Finally got around to testing this and it looks and sounds good!

**Pull request merged**
