### PR TITLE
Improved AnnularFusion with assignable CV mod

### PR DESCRIPTION
**Pull request by djphazer**
Updated design copied from qiemem with assignable CV modulation based on adegani's Euclid applet. Try it out, let me know if you notice any problems!

### CODE REVIEW

**Comment by benirose** [comment]
I couldn't get Euclid to run in Benispheres because they seemed to change everything from .ino to header files and I couldn't build, so I'm glad you put this together. I'll take a look, I'm still no the fence of the change in general, especially if you removed the visual display to make CV assignable, I might want to take a different approach. Regardless I'm pumped to take a look!

**Comment by djphazer** [comment]
I know, it's kind of a big deal, take your time to evaluate it... I was thinking we might even call it AnnularFusion2 or something else to distinguish it. I kept everything from qiemem's version (with the visual) and just added on... might still need visual tweaks tho, nudge a pixel here or there.

If you still want to try to build Euclid, you can grab [my copy](https://github.com/djphazer/O_C-BenisphereSuite/blob/phazerville/software/o_c_REV/HEM_Euclid.ino) that I already ported back to .ino and whatnot. It's functionally the same, the interface is just kinda boring!

**Comment by bowlneudel** [comment]
@djphazer Please ping me if you have the chance to re-integrate this version of Euclid into Benispheres 1.3!

I no longer have access to a system that can run Teensyduino 1.35, but if I can snag a hex from you I'd be very happy to test it. I'd just rather not miss out on these other new features 😁

**Comment by djphazer** [comment]
@bowlneudel shoot me an email - djphazer@gmail.com

**Comment by benirose** [comment]
I just shipped 1.3 but this is top of the list for next release!

**Pull request closed without merging**
