### PR TITLE
DrumMap applet

### PR DESCRIPTION
**Pull request by benirose**
This is a 2 channel port of Mutable Instruments Grids.

DrumMap is a 2-channel port of Mutable Instruments Grids. You are able to select any of the 3 parts to assign to each channel. In addition, the 2nd channel can be used as the accent channel of the 1st channel.

You can also change the CV Input assignment from “Part A Fill and Part B Fill”, “X and Y coordinates” and “Part A Fill and Chaos” (the last is useful when you’re using accent on channel 2, since it has no fill). CV is added to the parameter value set via the encoder, and voltages from -3 to +5 are supported. This means when the parameter is left in the middle, you should be able to use a +/-5 volt CV signal to reach both ends of the parameter. 

n order to make parameter changes more performable using the encoder, knob acceleration has been implemented for the "Fill", "X", "Y" and "Chaos" parameters. This means if you turn the knob quickly it will traverse the whole range, but if you turn it slowly it will increment by a single value. This works most of the time, but does occasionally get a little jumpy, due to the way it had to be implemented. 

In order to make room for this new app, I have disabled the following apps and applets:

o_C:
* Darkest Timeline
* Enigma
* Neural Network
* Pong

### CODE REVIEW

**Comment by benirose** [comment]
There is an issue with putting the step counter in the top right when clock forwarding is enabled. An alternative solution should be found.

**Comment by yratof** [comment]
Is this working with external clocks?

**Comment by benirose** [comment]
@yratof Yes external clocks are working, it expects a 32nd note clock on Digital 1.

**Comment by benirose** [comment]
There is a weird, intermittent bug in this branch which causes the module to freeze when DrumMap is on the left side and you are changing applets on the right side. Until this issue is addressed, this branch cannot be merged.

**Comment by benirose** [comment]
Given the low frequency of being able to replicate the bug I decided to move forward with merging this and releasing it as a beta to allow others to experiment with the new apps and report any issues they find.

**Comment by microcosmtoken** [comment]
32nd note -> Should this be faster, as the internal clock itself needs to be 150BPM at x8 for it to kick out a nice beat, but at the same time, the second app now is running super fast

**Comment by yratof** [comment]
Internal clock of hem needs to be set x4 / x8 when drum is looking for 32nd notes

**Comment by benirose** [comment]
I believe the bug was due to using the incorrect compiler optimization ("Fast" instead of "Faster") and I am no longer seeing them. I also addressed the overlap of the step count and the clock forwarding/internal clock icons. This is ready to merge!

**Pull request merged**
